name = "cf-worker-ws-dev7" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"

[vars]
# UUID = "dd206adb-2bb6-4864-97fd-6a32793e9ccc"
# PROXYIP = "36.69.20.244"
# DNS_RESOLVER_URL = "http://www.gstatic.com/generate_204"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "dd206adb-2bb6-4864-97fd-6a32793e9ccc"
