name = "cf-worker-ws-dev7" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"

[vars]
# UUID = "f4416912-c0c6-4aea-b9fe-59e4aeb81ba7"
# PROXYIP = "103.179.57.181"
# DNS_RESOLVER_URL = "http://www.gstatic.com/generate_204"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "f4416912-c0c6-4aea-b9fe-59e4aeb81ba7"
